/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Student_Managment;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import backend.*;
import java.io.IOException;
import java.util.List;
import services.CertificateService;
import services.CourseService;

/**
 *
 * @author zeyad
 */
public class CERTIFICATE extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CERTIFICATE.class.getName());

    /**
     * Creates new form CERTIFICATE
     */
    private Certificate cert;
    private String data[];
    private Student student;
    public CERTIFICATE(String courseID, Student student) {
        initComponents();
        this.student = student;
        this.cert = CertificateService.generateCertificate(courseID, student);
        System.out.println("STUDENT ENTERING GET CERTIFICATE DATA:\n" + cert.getstudentID());
        this.data = CertificateService.getCertificateData(cert).clone();
        this.studentName.setText(data[0]);
        this.courseName.setText(data[1]);
        this.courseID.setText(data[2]);
        this.InstructorName.setText(data[3]);
        this.DateField.setText(data[4]);
        this.certificateID.setText(data[5]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        courseName = new javax.swing.JLabel();
        courseID = new javax.swing.JLabel();
        studentName = new javax.swing.JLabel();
        InstructorName = new javax.swing.JLabel();
        DateField = new javax.swing.JLabel();
        certificateID = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/certificate_small.png"))); // NOI18N

        courseName.setForeground(new java.awt.Color(104, 104, 104));
        courseName.setText("course name");

        courseID.setForeground(new java.awt.Color(104, 104, 104));
        courseID.setText("courseID");

        studentName.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        studentName.setForeground(new java.awt.Color(0, 0, 102));
        studentName.setText("student name");

        InstructorName.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        InstructorName.setForeground(new java.awt.Color(104, 104, 104));
        InstructorName.setText("instructor name");

        DateField.setForeground(new java.awt.Color(104, 104, 104));
        DateField.setText("date");

        certificateID.setForeground(new java.awt.Color(104, 104, 104));
        certificateID.setText("certificateID");

        backButton.setText("back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        printButton.setText("print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel2, 2);
        jLayeredPane1.setLayer(courseName, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane1.setLayer(courseID, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane1.setLayer(studentName, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane1.setLayer(InstructorName, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane1.setLayer(DateField, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane1.setLayer(certificateID, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane1.setLayer(backButton, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane1.setLayer(printButton, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(courseID))
                            .addComponent(courseName))
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(studentName)
                        .addGap(87, 87, 87))))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DateField)
                    .addComponent(InstructorName))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(printButton)
                .addGap(38, 38, 38)
                .addComponent(certificateID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(28, 28, 28))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(studentName)
                .addGap(37, 37, 37)
                .addComponent(courseName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseID)
                .addGap(83, 83, 83)
                .addComponent(InstructorName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DateField)
                .addGap(53, 53, 53)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(certificateID)
                    .addComponent(backButton)
                    .addComponent(printButton))
                .addGap(16, 16, 16))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
        try{
            CertificateService.savePDF(cert, this.data.clone());
        }
        catch(IOException e){
            System.out.println("IO EXCEPTION FOUND!");
            e.printStackTrace(System.out);
        }
        
    }//GEN-LAST:event_printButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new Certificates(student).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateField;
    private javax.swing.JLabel InstructorName;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel certificateID;
    private javax.swing.JLabel courseID;
    private javax.swing.JLabel courseName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel studentName;
    // End of variables declaration//GEN-END:variables
}
