package User_Account_Management;
import backend.*;
import java.awt.Color;
import javax.swing.JFrame;
//import databaseservice.UserService;
public class Sign_up extends javax.swing.JFrame {
    
    JFrame frame = new JFrame();
    public Sign_up() {
        initComponents();
        setLocationRelativeTo(null);
    }
///////////////////////////////////////////////////////////  
      //1-add new user to files 
      //2-validation
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jFrame5 = new javax.swing.JFrame();
        jFrame6 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        userField1 = new javax.swing.JTextField();
        userField2 = new javax.swing.JTextField();
        userField0 = new javax.swing.JTextField();
        roleSelection = new javax.swing.JComboBox<>();
        emailField = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame5Layout = new javax.swing.GroupLayout(jFrame5.getContentPane());
        jFrame5.getContentPane().setLayout(jFrame5Layout);
        jFrame5Layout.setHorizontalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame5Layout.setVerticalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame6Layout = new javax.swing.GroupLayout(jFrame6.getContentPane());
        jFrame6.getContentPane().setLayout(jFrame6Layout);
        jFrame6Layout.setHorizontalGroup(
            jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame6Layout.setVerticalGroup(
            jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Blackadder ITC", 0, 10)); // NOI18N
        setForeground(java.awt.Color.white);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setToolTipText("LOGIN PAGE");
        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Rage Italic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sign up");

        jTextField2.setFont(new java.awt.Font("Informal Roman", 1, 48)); // NOI18N
        jTextField2.setText("LOGIN PAGE");
        jTextField2.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextField2.setVerifyInputWhenFocusTarget(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(118, 118, 118))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 310, 80));

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));
        jPanel4.setToolTipText("");

        userField1.setBackground(new java.awt.Color(0, 102, 153));
        userField1.setForeground(new java.awt.Color(153, 153, 153));
        userField1.setText("password");
        userField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        userField1.setCaretColor(new java.awt.Color(255, 255, 255));
        userField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userField1.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        userField1.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        userField1.setOpaque(true);
        userField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userField1FocusLost(evt);
            }
        });
        userField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userField1ActionPerformed(evt);
            }
        });

        userField2.setBackground(new java.awt.Color(0, 102, 153));
        userField2.setForeground(new java.awt.Color(153, 153, 153));
        userField2.setText("confirm password");
        userField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        userField2.setCaretColor(new java.awt.Color(255, 255, 255));
        userField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userField2.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        userField2.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        userField2.setOpaque(true);
        userField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userField2FocusLost(evt);
            }
        });
        userField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userField2ActionPerformed(evt);
            }
        });

        userField0.setBackground(new java.awt.Color(0, 102, 153));
        userField0.setForeground(new java.awt.Color(153, 153, 153));
        userField0.setText("username");
        userField0.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        userField0.setCaretColor(new java.awt.Color(255, 255, 255));
        userField0.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userField0.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        userField0.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        userField0.setOpaque(true);
        userField0.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userField0FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userField0FocusLost(evt);
            }
        });
        userField0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userField0ActionPerformed(evt);
            }
        });

        roleSelection.setBackground(new java.awt.Color(0, 51, 102));
        roleSelection.setForeground(new java.awt.Color(255, 255, 255));
        roleSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Instructor" }));
        roleSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleSelectionActionPerformed(evt);
            }
        });

        emailField.setBackground(new java.awt.Color(0, 102, 153));
        emailField.setForeground(new java.awt.Color(153, 153, 153));
        emailField.setText("email");
        emailField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        emailField.setCaretColor(new java.awt.Color(255, 255, 255));
        emailField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailField.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        emailField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        emailField.setOpaque(true);
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(roleSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userField1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userField0, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userField2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userField0, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(userField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userField2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 320, 260));

        login.setBackground(new java.awt.Color(0, 102, 153));
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("sign up");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 172, 39));

        jButton3.setBackground(new java.awt.Color(0, 51, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 100, 40));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String username = userField0.getText();
        String email = emailField.getText();
        String pass1 = userField1.getText();
        String pass2 = userField2.getText();
        String error_msg = "";
        if(!Validation.verifyName(username))
            error_msg += "username can only contain english letters, spaces or underscores!";
        if(!Validation.verifyPassword(pass1))
            error_msg += "password must be 8 characters or more!";
        if(!pass1.equals(pass2))
            error_msg += "passwords don't match!";
        if(error_msg.length() > 1)
            javax.swing.JOptionPane.showMessageDialog(frame, error_msg);
        else{
            String role = roleSelection.getSelectedItem().toString();
            User user;
            if(role.equals(UserService.StudentRole)){
                user = UserService.signup(username, email, pass1, role);
                
            }
            else if(role.equals(UserService.InstructorRole)){
                user = UserService.signup(username, email, pass1, role);
            }
            else{
                user = null;
            }
            if(user != null){
                this.dispose();
                new login().setVisible(true);
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(frame, "username or email already exists");
            }
        }

    }//GEN-LAST:event_loginActionPerformed

    private void userField0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userField0ActionPerformed


    }//GEN-LAST:event_userField0ActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked

    }//GEN-LAST:event_loginMouseClicked

    private void userField0FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userField0FocusGained
        if (userField0.getText().equals("username")) {
            userField0.setText("");
            userField0.setForeground(Color.white);
            Color c = new Color(0,102,153);
            userField0.setBackground(c);
        }
    }//GEN-LAST:event_userField0FocusGained

    private void userField0FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userField0FocusLost
        String input = userField0.getText();
        if (input.equals("")) {
            userField0.setText("username");
            userField0.setForeground(Color.GRAY);
        }
        if(!Validation.verifyName(input)){
            userField0.setBackground(Color.red);
        }
        else
            userField0.setBackground(Color.green);

    }//GEN-LAST:event_userField0FocusLost

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void userField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userField1FocusGained
        // TODO add your handling code here:
        if (userField1.getText().equals("password")) {
            userField1.setText("");
            userField1.setForeground(Color.white);
            Color c = new Color(0,102,153);
            userField1.setBackground(c);
        }
    }//GEN-LAST:event_userField1FocusGained

    private void userField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userField1FocusLost
        // TODO add your handling code here:
       String input = userField1.getText();
        if (input.equals("")) {
            userField1.setText("password");
            userField1.setForeground(Color.GRAY);
        }
        if(!Validation.verifyPassword(input)){
            userField1.setBackground(Color.red);
        }
        else
            userField1.setBackground(Color.green);
    }//GEN-LAST:event_userField1FocusLost

    private void userField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userField1ActionPerformed

    private void userField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userField2FocusGained
        // TODO add your handling code here
        if (userField2.getText().equals("confirm password")) {
            userField2.setText("");
            userField2.setForeground(Color.white);
            Color c = new Color(0,102,153);
            userField2.setBackground(c);
        }
    }//GEN-LAST:event_userField2FocusGained

    private void userField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userField2FocusLost
        // TODO add your handling code here:
        String input = userField2.getText();
        if (input.equals("")) {
            userField2.setText("confirm password");
            userField2.setForeground(Color.GRAY);
        }
        if(!Validation.verifyPassword(input)){
            userField2.setBackground(Color.red);
        }
        else
            userField2.setBackground(Color.green);
    }//GEN-LAST:event_userField2FocusLost

    private void userField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userField2ActionPerformed

    private void roleSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleSelectionActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       new welcome().setVisible(true);
       this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        // TODO add your handling code here:
        if (emailField.getText().equals("email")) {
            emailField.setText("");
            emailField.setForeground(Color.white);
            Color c = new Color(0,102,153);
            emailField.setBackground(c);
        }
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        // TODO add your handling code here:
        String input = emailField.getText();
        if (input.equals("")) {
            emailField.setText("email");
            emailField.setForeground(Color.GRAY);
        }
        if(!Validation.verifyEmail(input)){
            emailField.setBackground(Color.red);
        }
        else
            emailField.setBackground(Color.green);
    }//GEN-LAST:event_emailFieldFocusLost

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JFrame jFrame6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton login;
    private javax.swing.JComboBox<String> roleSelection;
    private javax.swing.JTextField userField0;
    private javax.swing.JTextField userField1;
    private javax.swing.JTextField userField2;
    // End of variables declaration//GEN-END:variables
}
