package Instructor_Management;

import javax.swing.*;
import java.awt.*;
import java.util.List;
import org.knowm.xchart.*;
import org.knowm.xchart.XChartPanel;

public class chart_dispalay extends javax.swing.JPanel {

    private final JFrame frame;

    public chart_dispalay() {
        // initComponents();
        setLayout(new BorderLayout()); // Important
        frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(650, 450);
        frame.add(this, BorderLayout.CENTER);
        frame.setLocationRelativeTo(null);
    }

    public void showChart(String Title, String xAxisTitle, String yAxisTitle, String seriesName, List<String> xData, List<Integer> yData,String title2,int avg) {

       
        JLabel label = new JLabel(title2+  avg);
        label.setHorizontalAlignment(SwingConstants.CENTER);
        label.setFont(new Font("Arial", Font.BOLD, 35));
        label.setBackground(Color.GRAY);   
        label.setOpaque(true);

        CategoryChart chart = new CategoryChartBuilder().width(600).height(400).title(Title).yAxisTitle(yAxisTitle).xAxisTitle(xAxisTitle).build();
        chart.addSeries(seriesName, xData, yData);
        
        // show chart in Panel
        this.removeAll();
        this.setLayout(new BorderLayout());
        this.add(label, BorderLayout.NORTH);
        this.add(new XChartPanel<>(chart), BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
        frame.setVisible(true);

    }

    public void showLessonProgressPie(String Title,String title2,Double percent, int completed, int notcompleted) {
      
        
        JLabel label = new JLabel(title2+ String.format("%.1f%%", percent));
        label.setHorizontalAlignment(SwingConstants.CENTER);
        label.setFont(new Font("Arial", Font.BOLD, 35));
        label.setBackground(Color.GRAY);
        
        label.setOpaque(true);

        
        PieChart pie = new PieChartBuilder().width(500).height(400).title(Title).build();

        pie.addSeries("Completed lessons", completed);
        pie.addSeries("Not Completed lessons", notcompleted);

        // Embed chart in panel
        XChartPanel<PieChart> panel = new XChartPanel<>(pie);

        // Show in JPanel
        this.removeAll();
        this.add(label, BorderLayout.NORTH);  
        this.add(panel, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
