package Instructor_Management;

import databaseservice.StudentService;
import databaseservice.CourseService;
import User_Account_Management.welcome;
import javax.swing.JFrame;
import backend.*;
import databaseservice.ProgressService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

public class view_enrolled_students extends javax.swing.JPanel {

    // private JFrame frame;
    private StudentService studentservice;
    String courseID;
    Course course;
    Instructor instructor;

    public view_enrolled_students(Instructor instructor, String courseID) {
        this.courseID = courseID;
        studentservice = new StudentService();
        CourseService manager = new CourseService();
        course = manager.getCoursebyid(courseID);
        List<String> students = course.getStudents();
        this.instructor = instructor;

        List<Course> courses = manager.getCoursesByInstructor(instructor);

        initComponents();
        loadStudentsToTable(students);

    }

    public void setVisible(boolean f) {
        if (f) {
            JFrame frame = new JFrame();
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.getContentPane().add(this);
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        }
    }

    ///////////////////////////////////////////////////////////  
      //1- LOAD IN TABELE FROM FILES AS NEEDED NOT ALL (DONT FORGET REMINDER)
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        EDIT_TABLE = new javax.swing.JScrollPane();
        enrolled = new javax.swing.JTable();
        viewquizscores = new javax.swing.JButton();
        viewlessonprogress = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setBackground(new java.awt.Color(153, 153, 153));

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("LOGOUT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel11.setText("ENROLLED STUDENT");

        enrolled.setAutoCreateRowSorter(true);
        enrolled.setBackground(new java.awt.Color(102, 102, 102));
        enrolled.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enrolled.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        enrolled.setForeground(new java.awt.Color(255, 255, 255));
        enrolled.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ahmed", "10000"}
            },
            new String [] {
                "ID", "NAME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enrolled.setToolTipText("MMM");
        enrolled.setFillsViewportHeight(true);
        enrolled.setGridColor(new java.awt.Color(255, 255, 255));
        enrolled.setShowGrid(true);
        enrolled.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                enrolledAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        enrolled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enrolledMouseClicked(evt);
            }
        });
        enrolled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enrolledKeyPressed(evt);
            }
        });
        EDIT_TABLE.setViewportView(enrolled);

        viewquizscores.setBackground(new java.awt.Color(102, 102, 102));
        viewquizscores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewquizscores.setForeground(new java.awt.Color(255, 255, 255));
        viewquizscores.setText("view quiz scores");
        viewquizscores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewquizscoresActionPerformed(evt);
            }
        });

        viewlessonprogress.setBackground(new java.awt.Color(102, 102, 102));
        viewlessonprogress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewlessonprogress.setForeground(new java.awt.Color(255, 255, 255));
        viewlessonprogress.setText("view lesson progress");
        viewlessonprogress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewlessonprogressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EDIT_TABLE, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(viewquizscores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewlessonprogress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel11)))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EDIT_TABLE, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewlessonprogress, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewquizscores, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JFrame topFrame = (JFrame) this.getTopLevelAncestor();
        topFrame.dispose();

        new Manage_Courses(instructor).setVisible(true);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        JFrame topFrame = (JFrame) this.getTopLevelAncestor();
        topFrame.dispose();

        new welcome().setVisible(true);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void enrolledAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_enrolledAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_enrolledAncestorAdded

    private void enrolledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrolledMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_enrolledMouseClicked

    private void enrolledKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enrolledKeyPressed

    }//GEN-LAST:event_enrolledKeyPressed

    private void viewquizscoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewquizscoresActionPerformed
        int row = enrolled.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a lesson to delete.");
            return;
        }
        if (row >= 0) {

            String studentId = enrolled.getValueAt(row, 0).toString();
            String studentname = enrolled.getValueAt(row, 1).toString();

            /*
             List<Integer> scores = ProgressService.getQuizMarksById(studentId,courseID);
             ArrayList<String> quizzes = new ArrayList();
             for (int i = 0; i < scores.size(); i++) {
                quizzes.add("quiz " + (i + 1));
            }
             int sum = 0;
             for (int score : scores) {
                sum += score;
            }*/
            
            //test
            List<Integer> scores = List.of(85, 90, 70);
            ArrayList<String> quizzes = new ArrayList();
            for (int i = 0; i < scores.size(); i++) {
                quizzes.add("quiz " + (i + 1));
            }
            int sum = 0;
            for (int score : scores) {
                sum += score;
            }

            chart_dispalay frame = new chart_dispalay();
            frame.setVisible(true);
            frame.showChart(
                    "Student Quiz Scores", // chartTitle
                    "Lessons", // xAxisTitle
                    "Score", // yAxisTitle
                    studentname, // seriesName
                    quizzes, // xData
                    scores,
                    "AVREAGE SCORE: ",
                    (sum / (scores.size() * 100)) // yData
            );

        } else {
            showMessageDialog(new javax.swing.JFrame(), "please select a lesson first");

        }
    }//GEN-LAST:event_viewquizscoresActionPerformed

    private void viewlessonprogressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewlessonprogressActionPerformed
        int row = enrolled.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a lesson to delete.");
            return;
        }
        if (row >= 0) {
            /*
            String studentId = enrolled.getValueAt(row, 0).toString();
            Course c=ob.getcoursebyid(courseID)
            int all =c.getcountlesson() ;// when course modified add get all count of lessons
            int completed = ProgressService.get_completedlessons_student(studentId, courseID);
          
            double progress = (double) completed / all;
             */
            //test
            int all = 17;
            int completed = 10;
            double progress = (double) completed / all;
            chart_dispalay frame = new chart_dispalay();
            frame.setVisible(true);
            frame.showLessonProgressPie("lesson progress", "PROGRESS IN COURSE: ", progress*100, completed, all - completed);

        } else {
            showMessageDialog(new javax.swing.JFrame(), "please select a lesson first");

        }
    }//GEN-LAST:event_viewlessonprogressActionPerformed

    private void loadStudentsToTable(List<String> studentIDs) {

        DefaultTableModel model
                = (DefaultTableModel) enrolled.getModel();

        model.setRowCount(0);

        for (String id : studentIDs) {
            Student s = (Student) studentservice.getStudentbyid(id);
            if (s != null) {
                Object[] row = {
                    s.getUserId(),
                    s.getUsername(),};
                model.addRow(row);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane EDIT_TABLE;
    public javax.swing.JTable enrolled;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewlessonprogress;
    private javax.swing.JButton viewquizscores;
    // End of variables declaration//GEN-END:variables
}
