
package Instructor_Management;
import databaseservice.StudentService;
import databaseservice.CourseService;
import User_Account_Management.welcome;
import javax.swing.JFrame;
import backend.*;
import java.util.List;

public class view_enrolled_students extends  javax.swing.JPanel {

   // private JFrame frame;
    private StudentService studentservice;
    String courseID;
    Course course;
    Instructor instructor;
  
    public view_enrolled_students(Instructor instructor,String courseID) {
        this.courseID = courseID;
        studentservice = new StudentService();
        CourseService manager = new CourseService();
        course = manager.getCoursebyid(courseID);
        List<String> students = course.getStudents();
        this.instructor = instructor;
        
        List<Course> courses = manager.getCoursesByInstructor(instructor) ;
        
        initComponents();
        loadStudentsToTable(students);

    }
     
    public void setVisible(boolean f) {
        if (f) {
            JFrame frame = new JFrame();
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.getContentPane().add(this);
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        }
    }
       ///////////////////////////////////////////////////////////  
      //1- LOAD IN TABELE FROM FILES AS NEEDED NOT ALL (DONT FORGET REMINDER)
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        EDIT_TABLE = new javax.swing.JScrollPane();
        enrolled = new javax.swing.JTable();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setBackground(new java.awt.Color(153, 153, 153));

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("LOGOUT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel11.setText("ENROLLED STUDENT");

        enrolled.setAutoCreateRowSorter(true);
        enrolled.setBackground(new java.awt.Color(102, 102, 102));
        enrolled.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enrolled.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        enrolled.setForeground(new java.awt.Color(255, 255, 255));
        enrolled.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ahmed", "10000", "100"}
            },
            new String [] {
                "ID", "NAME", "PROGRESS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enrolled.setToolTipText("MMM");
        enrolled.setFillsViewportHeight(true);
        enrolled.setGridColor(new java.awt.Color(255, 255, 255));
        enrolled.setShowGrid(true);
        enrolled.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                enrolledAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        enrolled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enrolledMouseClicked(evt);
            }
        });
        enrolled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enrolledKeyPressed(evt);
            }
        });
        EDIT_TABLE.setViewportView(enrolled);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EDIT_TABLE, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(388, 388, 388)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel11)))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EDIT_TABLE, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    JFrame topFrame = (JFrame) this.getTopLevelAncestor();
    topFrame.dispose();

        new Manage_Courses(instructor).setVisible(true);
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  
            JFrame topFrame = (JFrame) this.getTopLevelAncestor();
    topFrame.dispose();
        
        new welcome().setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void enrolledAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_enrolledAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_enrolledAncestorAdded

    private void enrolledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrolledMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_enrolledMouseClicked

    private void enrolledKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enrolledKeyPressed

    }//GEN-LAST:event_enrolledKeyPressed

    
    
    
    
    
    private void loadStudentsToTable(List<String> studentIDs) {
   
    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) enrolled.getModel();

   
    model.setRowCount(0);

   
    
    for (String id : studentIDs) {
        Student s = (Student) studentservice.getStudentbyid(id);
        List<progress> progress = s.getProgress();
        progress p = studentservice.getProgressByCourseId(progress, courseID);
        if (s != null) {
            Object[] row = {
                s.getUserId(),
                s.getUsername(),
                p.getProgressPercentagebycourse(course)
                    
            };

            model.addRow(row);
        }
    }
}
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane EDIT_TABLE;
    public javax.swing.JTable enrolled;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
